eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${server.eureka}/eureka/
management: 
  endpoint: 
    metrics: 
      enabled: true
    prometheus: 
      enabled: true
  endpoints: 
    web: 
      exposure: 
        include: "*"
  metrics: 
    export: 
      prometheus: 
        enabled: true
spring: 
  application: 
    name: consumerdatastandards
  data: 
    mongodb: 
      uri: mongodb://${server.mongodb.uri}/AccountsAPI
  jackson: 
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles: 
    active: local
  sleuth: 
    sampler: 
      percentage: 1
  zipkin: 
    base-url: http://${server.zipkin}
